### ISSUE TITLE
HamburgerMenu with Prism Unity

### ISSUE THREAD

**Issue by Jeremywhiteley** [PrismLibrary/Prism-Samples-Forms#16]
Is there an sample of the HamburgerMenu done with Prism Unity?   The sample here is using something else.

**Comment by brianlagunas** [comment]
What do you mean "using something else"?  That is a Prism app with a MasterDetailPage.  What exactly are you expecting?

**Comment by ahoefling** [comment]
I recently followed the example here to implement a MasterDetailPage. I will note that when completed I didn't get the exact behavior I was expecting on iOS vs android where Android was giving me exactly what I expected. After speaking with a few iOS devs I know they told me everything made sense on how the iOS navigation was working.

All of my issues were with the look and feel of the MasterDetailPage and not the functionality. Let me know and I can go into detail some of the things I noticed.

**Comment by rastreus** [comment]
@brianlagunas I may be wrong, but I think what was trying to be expressed with "using something else" is that the current HamburgerMenu example uses the DryIoc container rather than Unity--which is typically the default IoC container for Prism and its examples.

@Jeremywhiteley The structure of the example does't change, but if you wanted to use Unity rather than DryIoc, you would do the following in the App.xaml.cs file:

- Include Unity with `using Microsoft.Practices.Unity;`
- In RegisterTypes, register the AuthenticationService using Unity's syntax rather than the current DryIoc syntax with `Container.RegisterType<IAuthenticationService, AuthenticationService>(new ContainerControlledLifetimeManager());`

Afaik, that's all that needs to be changed; this isn't a real issue.

**Comment by brianlagunas** [comment]
Yes @rastreus you are correct.  From an API and feature perspective not much changes.  Only any container specific features that are used.
