### ISSUE TITLE
XamlCTask fails unexpectedly

### ISSUE THREAD

**Issue by HMDodd01** [PrismLibrary/Prism-Samples-Forms#34]
I downloaded the repro and opened the hamburger menu solution. When I build it, it gives me the error "The XamlCTask failed unexpectedly". I just want to compare my hamburger menu solution to yours on a device to see if your android application has the same navigation issue as mine.

My problem: I'm on a detail page and switch to another detail page via the menu. When I hit the back button, it backs me all the way out of the app instead of the detail page that I was just on. I've followed the hamburger solution code but I want to see it work on an android device so see if you have the same issue as me or if I've done something wrong. Thanks

**Comment by brianlagunas** [comment]
This normally indicates that your file paths are too long. Shorten your file path to something like C:/temp and try again.

**Comment by brianlagunas** [comment]
Also, in Xamarin.Forms, when you change detail of a MDP, that is not going to respect a "go back" because technically changing the MDP Detail is not a navigation action.  You will need to reuse a NaviagtionPage as the Detail wrapper in order to achieve your desired results.  Create a custom NavPage and implement INavigationPageOptions and set the ClearNavigationStackOnNavigation propert to false.

**Comment by brianlagunas** [comment]
Also, in Xamarin.Forms, when you change detail of a MDP, that is not going to respect a "go back" because technically changing the MDP Detail is not a navigation action.  You will need to reuse a NaviagtionPage as the Detail wrapper in order to achieve your desired results.  Create a custom NavPage and implement INavigationPageOptions and set the ClearNavigationStackOnNavigation propert to false.

**Comment by HMDodd01** [comment]
I tried making a wrapped Detail page before but I didn't use the interface. Thanks for the help! Now that it works, is there a way to get rid of the back button in the nav bar so that the hamburger menu button shows up instead? The "HasBackButton=false" on the NavigationPage doesn't get rid of the back button. Thanks again for the help!
