### ISSUE TITLE
[05-EventAggregator] fail to update the "feedback" on Android

### ISSUE THREAD

**Issue by geosom** [PrismLibrary/Prism-Samples-Forms#98]
### Description

The sample "**05-EventAggregator**" work well on Ios. But on Android, HomePage not updated when changing a Feedback. I use VS4Mac 2019. 

### To reproduce

- Build and launch the sample "05-EventAggregator" on Android
- Click on "XAMARIN.FORMS EVENTS", the feedback is unselected on Home Page
- Click on "PROVIDE FEEDBACK", change the feedback and "SUBMIT"
- When the app redirected to Home Page, the feedback is not updated

**Comment by jbachelor** [comment]
Hi @geosom,

I am unable to replicate this behavior you describe. When I follow your exact steps, both Android and iOS seem to work correctly, and identically. I tried adding Debug.WriteLine statements to all of the methods in the (thankfully small) solution, and the only difference I see is what you would expect:  When running on Android, a subscription to the `NativeEvent` occurs in `MainActivity.OnCreate` while on iOS that same subscription occurs in `AppDelegate.FinishedLaunching`.

![image](https://user-images.githubusercontent.com/19045/86537990-f22be400-bea7-11ea-99a3-4bec3d56275b.png)

I do have one guess as to what you may have noticed:  After you complete the steps in your post above, if you then tap on "PROVIDE FEEDBACK" a second time (now that "Isn't this fun?" has been set to `true`) we get an interesting situation. When the DataEntryPage comes up, the switch is always set to `false` by default, regardless of what it was in the `HomePageViewModel`.

If at that point, you simply tap the "SUBMIT" button, you would reasonably expect the `IsFun` property in the `HomePageViewModel` to update to false, which would trigger the switch back to the `false` position.

However, since the `IsFunChangedEvent` is only published when the value of `DataEntryPageViewModel.IsFun` changes, you get no change in the `HomePageViewModel.IsFun` property:
```csharp
private bool _isFun;
public bool IsFun
{
    get => _isFun;
    set => SetProperty(ref _isFun, value, () => _eventAggregator.GetEvent<IsFunChangedEvent>().Publish(value));
}
```

The above code snippet [can be seen here](https://github.com/PrismLibrary/Prism-Samples-Forms/blob/b967ddc68d4cc7f0ed08b589fe18f5d1af126991/05-EventAggregator/src/PrismSample/ViewModels/DataEntryPageViewModel.cs#L24).

Any chance that is the issue you were noticing?
